version: '3'

services:
  api_pagination:
    container_name: api_pagination
    restart: unless-stopped
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/PaginationAPI/
    command: python manage.py runserver --host 0.0.0.0
    networks:
      - pagination

networks:
  pagination:
    driver: bridge

